// server/modules/iam/catalogs/professions.es.js
export const PROFESIONES_OFICIOS = [
  "Administrador/a",
  "Asistente administrativo/a",
  "Secretaria/o",
  "Recepcionista",
  "Archivista",
  "Oficinista",
  "Gerente de Recursos Humanos",
  "Gerente General",
  "Supervisor/a",
  "Contador/a",
  "Auxiliar contable",
  "Auditor/a",
  "Analista financiero",
  "Cajero/a",
  "Abogado/a",
  "Notario/a",
  "Juez / Jueza",
  "Fiscal",
  "Asesor/a legal",
  "Médico/a General",
  "Médico/a Especialista",
  "Cirujano/a",
  "Odontólogo/a (Dentista)",
  "Enfermero/a",
  "Auxiliar de enfermería",
  "Paramédico/a",
  "Técnico/a en Laboratorio Clínico",
  "Farmacéutico/a",
  "Nutricionista",
  "Fisioterapeuta",
  "Psicólogo/a",
  "Trabajador/a Social en Salud",
  "Veterinario/a",
  "Docente de Prebásica",
  "Docente de Educación Básica",
  "Docente de Secundaria",
  "Profesor/a Universitario/a",
  "Tutor/a",
  "Orientador/a Educativo/a",
  "Pedagogo/a",
  "Psicopedagogo/a",
  "Ingeniero/a en Sistemas",
  "Desarrollador/a de Software",
  "Programador/a",
  "Analista de Sistemas",
  "Administrador/a de Bases de Datos",
  "Administrador/a de Redes",
  "Soporte Técnico",
  "Técnico/a en Informática",
  "Especialista en Ciberseguridad",
  "Diseñador/a Web",
  "Tester / QA",
  "Ingeniero/a Civil",
  "Ingeniero/a Industrial",
  "Ingeniero/a Eléctrico",
  "Ingeniero/a Mecánico",
  "Ingeniero/a Electrónico",
  "Ingeniero/a Agrónomo",
  "Ingeniero/a Ambiental",
  "Ingeniero/a Químico",
  "Ingeniero/a en Telecomunicaciones",
  "Guardia de Seguridad",
  "Policía",
  "Militar",
  "Bombero/a",
  "Inspector/a de Seguridad",
  "Vigilante",
  "Vendedor/a",
  "Ejecutivo/a de Ventas",
  "Representante Comercial",
  "Mercadólogo/a",
  "Promotor/a",
  "Dependiente de tienda",
  "Encargado/a de Bodega",
  "Logístico/a",
  "Albañil",
  "Carpintero/a",
  "Plomero / Fontanero",
  "Electricista",
  "Soldador/a",
  "Pintor/a",
  "Herrero/a",
  "Yesero/a",
  "Maestro de Obras",
  "Topógrafo/a",
  "Chofer",
  "Taxista",
  "Conductor de Bus",
  "Conductor de Camión",
  "Piloto",
  "Ayudante de Transporte",
  "Coordinador de Transporte",
  "Mesero/a",
  "Cocinero/a",
  "Chef",
  "Barista",
  "Bartender",
  "Recepcionista de Hotel",
  "Camarero/a de Hotel",
  "Personal de Limpieza",
  "Conserje",
  "Estilista",
  "Barbero",
  "Manicurista / Pedicurista",
  "Periodista",
  "Reportero/a",
  "Locutor/a",
  "Comunicador/a Social",
  "Diseñador/a Gráfico",
  "Fotógrafo/a",
  "Camarógrafo/a",
  "Editor/a de Video",
  "Músico/a",
  "Actor / Actriz",
  "Productor/a Audiovisual",
  "Agricultor/a",
  "Ganadero/a",
  "Jornalero/a",
  "Jardinero/a",
  "Operador/a de Maquinaria",
  "Obrero/a de Fábrica",
  "Panadero/a",
  "Carnicero/a",
  "Empresario/a",
  "Comerciante",
  "Trabajador/a Independiente",
  "Ama de Casa",
  "Estudiante",
  "Desempleado/a",
  "Otro",
];

export default PROFESIONES_OFICIOS;